# Generated by Django 3.0.5 on 2020-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUIVSaveGame', '0002_euivsavegame_host_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euivsavegame',
            name='savegame_name',
            field=models.CharField(db_index=True, default='Savegame name', help_text='The name of the savegame to use.', max_length=50, unique=True, verbose_name='Savegame name'),
        ),
    ]
