# Generated by Django 3.0.5 on 2020-04-26 22:14

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EUIVSaveGame', '0003_auto_20200426_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='euivsavegame',
            name='hits_until_end_of_record',
            field=models.IntegerField(default=3, help_text='The number of savegame process without changes until the end of stream.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Record max hits'),
        ),
        migrations.AlterField(
            model_name='euivsavegame',
            name='savegame_name',
            field=models.CharField(db_index=True, default=uuid.UUID('ca7bc120-19a6-40bc-aa9b-f5f6a9511ce4'), help_text='The name of the savegame to use.', max_length=50, unique=True, verbose_name='Savegame name'),
        ),
    ]
