# Generated by Django 3.0.5 on 2020-04-26 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EUIVSaveGame', '0004_auto_20200427_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='euivsavegame',
            old_name='hits_until_end_of_record',
            new_name='hits_until_end_of_streaming',
        ),
        migrations.AlterField(
            model_name='euivsavegame',
            name='savegame_name',
            field=models.CharField(db_index=True, default=uuid.UUID('7ebbe6dc-ba51-4dce-a5fe-40f66b2fe6cf'), help_text='The name of the savegame to use.', max_length=50, unique=True, verbose_name='Savegame name'),
        ),
    ]
