# Generated by Django 3.0.5 on 2020-04-12 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EUIVSaveGame', '0002_euivsavegame_host_user'),
        ('EUIVCountries', '0003_euivprovince'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuIVProvinceStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime when de object was created.', null=True, verbose_name='Creation datetime')),
                ('modification_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='Datetime of the last object modification.', null=True, verbose_name='Modification datetime')),
                ('stats_date', models.DateField(blank=True, db_index=True, help_text='Current date in the savegame when the screenshot.', null=True, verbose_name='Stats date')),
                ('development', models.FloatField(blank=True, help_text='Current development of the province.', null=True, verbose_name='Development')),
                ('base_tax', models.FloatField(blank=True, help_text='Current base tax of the province.', null=True, verbose_name='Base Tax')),
                ('base_production', models.FloatField(blank=True, help_text='Current base production of the province.', null=True, verbose_name='Base production')),
                ('base_manpower', models.FloatField(blank=True, help_text='Current base manpower of the province.', null=True, verbose_name='Base manpower')),
                ('trade_power', models.FloatField(blank=True, help_text='Current trade power of the province.', null=True, verbose_name='Trade power')),
                ('devastation', models.FloatField(blank=True, help_text='Current devastation of the province.', null=True, verbose_name='Devastation')),
                ('controller', models.ForeignKey(blank=True, help_text='Current controller of the province.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_controller', to='EUIVCountries.EuIVCountry', verbose_name='Controller')),
                ('owner', models.ForeignKey(blank=True, help_text='Current owner of the province.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_owner', to='EUIVCountries.EuIVCountry', verbose_name='Owner')),
                ('province', models.ForeignKey(blank=True, help_text='Current province for the info.', null=True, on_delete=django.db.models.deletion.CASCADE, to='EUIVCountries.EuIVProvince', verbose_name='Province')),
                ('save_game', models.ForeignKey(blank=True, help_text='Save game associated to the province info.', null=True, on_delete=django.db.models.deletion.CASCADE, to='EUIVSaveGame.EuIVSaveGame', verbose_name='Save game')),
            ],
            options={
                'verbose_name': 'Province stat',
            },
        ),
    ]
