# Generated by Django 3.0.5 on 2020-04-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EUIVSaveGame', '0001_initial'),
        ('EUIVCountries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuIVProvinceStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime when de object was created.', null=True, verbose_name='Creation datetime')),
                ('modification_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='Datetime of the last object modification.', null=True, verbose_name='Modification datetime')),
                ('stats_date', models.DateField(blank=True, db_index=True, help_text='Current date in the savegame when the screenshot.', null=True, verbose_name='Stats date')),
                ('development', models.FloatField(blank=True, help_text='Current development of the province.', null=True, verbose_name='Development')),
                ('base_tax', models.FloatField(blank=True, help_text='Current base tax of the province.', null=True, verbose_name='Base Tax')),
                ('base_production', models.FloatField(blank=True, help_text='Current base production of the province.', null=True, verbose_name='Base production')),
                ('base_manpower', models.FloatField(blank=True, help_text='Current base manpower of the province.', null=True, verbose_name='Base manpower')),
                ('trade_power', models.FloatField(blank=True, help_text='Current trade power of the province.', null=True, verbose_name='Trade power')),
                ('devastation', models.FloatField(blank=True, help_text='Current devastation of the province.', null=True, verbose_name='Devastation')),
                ('controller', models.ForeignKey(blank=True, help_text='Current controller of the province.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_controller', to='EUIVCountries.EuIVCountry', verbose_name='Controller')),
                ('owner', models.ForeignKey(blank=True, help_text='Current owner of the province.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_owner', to='EUIVCountries.EuIVCountry', verbose_name='Owner')),
                ('province', models.ForeignKey(blank=True, help_text='Current province for the info.', null=True, on_delete=django.db.models.deletion.CASCADE, to='EUIVCountries.EuIVProvince', verbose_name='Province')),
                ('save_game', models.ForeignKey(blank=True, help_text='Save game associated to the province info.', null=True, on_delete=django.db.models.deletion.CASCADE, to='EUIVSaveGame.EuIVSaveGame', verbose_name='Save game')),
            ],
            options={
                'verbose_name': 'Province stat',
            },
        ),
        migrations.CreateModel(
            name='EuIVCountryStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime when de object was created.', null=True, verbose_name='Creation datetime')),
                ('modification_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='Datetime of the last object modification.', null=True, verbose_name='Modification datetime')),
                ('stats_date', models.DateField(blank=True, db_index=True, help_text='Current date in the savegame when the screenshot.', null=True, verbose_name='Stats date')),
                ('current_power_projection', models.FloatField(blank=True, help_text='Current power projection of the country.', null=True, verbose_name='Power projection')),
                ('great_power_score', models.FloatField(blank=True, help_text='Current great power score of the country.', null=True, verbose_name='Great power score')),
                ('development', models.FloatField(blank=True, help_text='Current development of the country.', null=True, verbose_name='Development')),
                ('raw_development', models.FloatField(blank=True, help_text='Current raw development of the country.', null=True, verbose_name='Raw development')),
                ('capped_development', models.FloatField(blank=True, help_text='Current capped development of the country.', null=True, verbose_name='Capped development')),
                ('realm_development', models.FloatField(blank=True, help_text='Current realm development of the country.', null=True, verbose_name='Realm development')),
                ('base_tax', models.FloatField(blank=True, help_text='Current base tax of the country.', null=True, verbose_name='Base tax')),
                ('adm_tech', models.IntegerField(blank=True, help_text='Current administrative technology of the country.', null=True, verbose_name='Administrative technology')),
                ('dip_tech', models.IntegerField(blank=True, help_text='Current diplomatic technology of the country.', null=True, verbose_name='Diplomatic technology')),
                ('mil_tech', models.IntegerField(blank=True, help_text='Current military technology of the country.', null=True, verbose_name='Military technology')),
                ('navy_strength', models.FloatField(blank=True, help_text='Current navy strength of the country.', null=True, verbose_name='Navy strength')),
                ('num_owned_home_cores', models.IntegerField(blank=True, help_text='Current total owned home cores of the country.', null=True, verbose_name='Total owned home cores')),
                ('num_of_controlled_cities', models.IntegerField(blank=True, help_text='Current total controlled cities of the country.', null=True, verbose_name='Total controlled cities')),
                ('num_of_total_ports', models.IntegerField(blank=True, help_text='Current total ports of the country.', null=True, verbose_name='Total ports')),
                ('forts', models.IntegerField(blank=True, help_text='Current forts of the country.', null=True, verbose_name='Forts')),
                ('average_effective_unrest', models.FloatField(blank=True, help_text='Current average unrest of the country.', null=True, verbose_name='Average unrest')),
                ('average_autonomy', models.FloatField(blank=True, help_text='Current autonomy of the country.', null=True, verbose_name='Average autonomy')),
                ('num_of_allies', models.IntegerField(blank=True, help_text='Current total allies of the country.', null=True, verbose_name='Total allies')),
                ('prestige', models.FloatField(blank=True, help_text='Current prestige of the country.', null=True, verbose_name='Prestige')),
                ('stability', models.FloatField(blank=True, help_text='Current stability of the country.', null=True, verbose_name='Stability')),
                ('treasury', models.FloatField(blank=True, help_text='Current treasury of the country.', null=True, verbose_name='Treasury')),
                ('inflation', models.FloatField(blank=True, help_text='Current inflation of the country.', null=True, verbose_name='Inflation')),
                ('total_owned_provinces', models.IntegerField(blank=True, help_text='Current total owned provinces of the country.', null=True, verbose_name='Total owned provinces')),
                ('total_controlled_provinces', models.IntegerField(blank=True, help_text='Current total controlled provinces of the country.', null=True, verbose_name='Total controlled provinces')),
                ('army_tradition', models.FloatField(blank=True, help_text='Current army tradition of the country.', null=True, verbose_name='Army tradition')),
                ('navy_tradition', models.FloatField(blank=True, help_text='Current navy tradition of the country.', null=True, verbose_name='Navy tradition')),
                ('last_month_income', models.FloatField(blank=True, help_text='Current last month income of the country.', null=True, verbose_name='Last month income')),
                ('last_month_expense', models.FloatField(blank=True, help_text='Current last month expense of the country.', null=True, verbose_name='Last month expense')),
                ('estimated_loan', models.FloatField(blank=True, help_text='Current estimated loan of the country.', null=True, verbose_name='Estimated loan')),
                ('corruption', models.FloatField(blank=True, help_text='Current corruption of the country.', null=True, verbose_name='Corruption')),
                ('legitimacy', models.FloatField(blank=True, help_text='Current legitimacy of the country.', null=True, verbose_name='Legitimacy')),
                ('mercantilism', models.FloatField(blank=True, help_text='Current mercantilism of the country.', null=True, verbose_name='Mercantilism')),
                ('splendor', models.FloatField(blank=True, help_text='Current splendor of the country.', null=True, verbose_name='Splendor')),
                ('army_professionalism', models.FloatField(blank=True, help_text='Current army professionalism of the country.', null=True, verbose_name='Army professionalism')),
                ('government', models.CharField(blank=True, help_text='Current government of the country.', max_length=50, null=True, verbose_name='Government')),
                ('manpower', models.FloatField(blank=True, help_text='Current manpower of the country.', null=True, verbose_name='Manpower')),
                ('max_manpower', models.FloatField(blank=True, help_text='Current max manpower of the country.', null=True, verbose_name='Max manpower')),
                ('sailors', models.FloatField(blank=True, help_text='Current sailors of the country.', null=True, verbose_name='Sailors')),
                ('max_sailors', models.FloatField(blank=True, help_text='Current max sailors of the country.', null=True, verbose_name='Max sailors')),
                ('is_great_power', models.BooleanField(db_index=True, default=False, help_text='Indicate if the country is great power.', verbose_name='Great power')),
                ('government_reform_progress', models.FloatField(blank=True, help_text='Current max sailors of the country.', null=True, verbose_name='Government reform progress')),
                ('country', models.ForeignKey(blank=True, help_text='Current country for the info.', null=True, on_delete=django.db.models.deletion.CASCADE, to='EUIVCountries.EuIVCountry', verbose_name='Country')),
                ('save_game', models.ForeignKey(blank=True, help_text='Save game associated to the country info.', null=True, on_delete=django.db.models.deletion.CASCADE, to='EUIVSaveGame.EuIVSaveGame', verbose_name='Save game')),
            ],
            options={
                'verbose_name': 'Country stat',
            },
        ),
    ]
