# Generated by Django 3.0.5 on 2020-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EuIVCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime when de object was created.', null=True, verbose_name='Creation datetime')),
                ('modification_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='Datetime of the last object modification.', null=True, verbose_name='Modification datetime')),
                ('tag', models.CharField(db_index=True, help_text='Internal EUIV tag for countries.', max_length=6, unique=True, verbose_name='Country tag')),
                ('name', models.CharField(blank=True, db_index=True, default='Country', help_text='Complete name of the country', max_length=50, null=True, verbose_name='Country name')),
                ('color', models.CharField(blank=True, default='000, 000, 000', help_text='Color of the country in RGB way with comma separator (000, 000, 000)', max_length=19, null=True, verbose_name='Country color')),
            ],
            options={
                'verbose_name': 'Countrie',
            },
        ),
        migrations.CreateModel(
            name='EuIVProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime when de object was created.', null=True, verbose_name='Creation datetime')),
                ('modification_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='Datetime of the last object modification.', null=True, verbose_name='Modification datetime')),
                ('identifier', models.CharField(db_index=True, help_text='Internal EUIV identifier for provinces.', max_length=6, unique=True, verbose_name='Province identifier')),
                ('name', models.CharField(blank=True, db_index=True, default='Province', help_text='Complete name of the province', max_length=50, null=True, verbose_name='Province name')),
            ],
            options={
                'verbose_name': 'Province',
            },
        ),
    ]
