# Generated by Django 3.0.5 on 2020-04-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUIVCountries', '0002_populate_countries_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuIVProvince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Datetime when de object was created.', null=True, verbose_name='Creation datetime')),
                ('modification_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='Datetime of the last object modification.', null=True, verbose_name='Modification datetime')),
                ('identifier', models.CharField(db_index=True, help_text='Internal EUIV identifier for provinces.', max_length=6, unique=True, verbose_name='Province identifier')),
                ('name', models.CharField(blank=True, db_index=True, default='Province', help_text='Complete name of the province', max_length=50, null=True, verbose_name='Country name')),
            ],
            options={
                'verbose_name': 'Province',
            },
        ),
    ]
