# Generated by Django 3.0.5 on 2020-04-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUIVCountries', '0003_euivprovince'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euivprovince',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Province', help_text='Complete name of the province', max_length=50, null=True, verbose_name='Province name'),
        ),
    ]
