# Generated by Django 3.0.5 on 2020-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUIVCountries', '0004_auto_20200413_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='euivcountry',
            name='color',
            field=models.CharField(blank=True, default='000, 000, 000', help_text='Color of the country in RGB way with comma separator (000, 000, 000)', max_length=19, null=True, verbose_name='Country color'),
        ),
    ]
